// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szadwvnchkaabtuygnok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6YWR3dm5jaGthYWJ0dXlnbm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjM1NzcsImV4cCI6MjA1OTUzOTU3N30.SdMlGgXthZVhOmXVkT6tZwfpSMtslXeEN6QE18opjWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);